### ISSUE TITLE
script/deploy ?

### ISSUE THREAD

**Issue by jesperronn** [github/scripts-to-rule-them-all#11]
Did you consider a generic name for a deploy script file as well? I am surprised that it's not here in this repository. 

However, I realize that the actual deployment is very specific for every project. Which means that the content of the file could differ. But still, the naming convention would prevail.

I vote for a `script/deploy` file :+1:

**Comment by maddox** [comment]
> However, I realize that the actual deployment is very specific for every project. Which means that the content of the file could differ.

This is totally fair though. This is one of the primary goals of STRTA. To mask away the business logic and complexity required to do these things with a single familiar command.

In the world of continuous deployment, I think this would be good. While it wouldn't be there for normalizations for contributors/maintainers, a normalized script name would help building automated deploy tools easier. This would be in the same vein as `script/cibuild`.

**Comment by jesperronn** [comment]
Exactly my point! How to implement the contents is a different story. Firstly, we would probably just need an 'empty' file with some guidance text to serve as `script/deploy`

**Comment by technicalpickles** [comment]
We do actually have a pattern for `script/deploy`, but it's pretty steeped in how our deploy system (heaven) works. 

In brief, heaven is a web interface for multiple projects using capistrano. If a project works well in the context of capistrano (ie update some code, restart some daemon), there's no extra config necessary. For projects that doesn't quite fit, heaven supports running a `script/deploy` command from the most recent checkout. I've seen this mostly this used when generating an artificat, and then doing something with that. 

So, could it be described in the README? Sure. Do we have any guidance for what to do with a `script/deploy`? I don't have anything concrete to suggest yet.

**Comment by mikemcquaid** [comment]
I think this is worth closing out as it's not something we use regularly internally and it would be too GitHub-specific to be useful.

**Comment by exalted** [comment]
I think `script/deploy` is worth considering to include into this repo and in the README. I can see `script/cibuild` ending like this:

```
[…]
# run tests.
script/test

# deploy
echo "Deploying …"
date "+%H:%M:%S"

# deploy.
script/deploy
```

**Comment by MikeMcQuaid** [comment]
As mentioned earlier @exalted: 

> it's not something we use regularly internally and it would be too GitHub-specific to be useful.

This repo is about documenting GitHub's patterns and this isn't one we use, sorry.

**Comment by exalted** [comment]
✌️


Ali
