### ISSUE TITLE
script/lint ?

### ISSUE THREAD

**Issue by jesperronn** [github/scripts-to-rule-them-all#12]
Is there an existing place where you would put in your linting steps. This could be

* rubocop/brakeman (for ruby)
* jscs/jshint (for javascript)
* codenarc (for groovy)
* pmd (for java)

etc.

Either put it in as a separate linter script or place it as part of script/test

What do you think?

**Comment by technicalpickles** [comment]
I've only used linters in a handful of projects, but when I do I just put them in `script/test` so they are part of the normal CI workflow.

**Comment by jesperronn** [comment]
For me, it depends on the project style, language, etc. For Js (and partially for ruby) I tend to keep it before the tests, to make my test job fail if the linter fails. 

My preference would be to keep lint as a separate script, and call it from the test script.

**Comment by maddox** [comment]
:+1:

**Comment by maddox** [comment]
@technicalpickles :+1: agreed.

@jesperronn if that's the case, then just put it first in `script/test`. This other thing is, you could always break out both into their own scripts, then call them both from `script/test`. 

That:

1. Keeps with the nature of reusability.
2. Exposes the tasks easily to people that peek into `script/` that might want to manually run the linter.

**Comment by jesperronn** [comment]
OK thanks for guidance :) :+1:
