### ISSUE TITLE
script/release ?

### ISSUE THREAD

**Issue by jesperronn** [github/scripts-to-rule-them-all#13]
Don't know about github. But I am seeing a lot of projects which must release versions of software. 

This is especially true for rubygems, plugins for js, and grails/java in general.

Do you see a default script to put code which has to do with releasing?

This could include

* bump a version (major,minor,patch)
* update a changelog
* tag a git commit
* push to external repository (rubygems, npm, bower, grails plugins, bintray, etc...)

Any thoughts on this?

**Comment by maddox** [comment]
Releasing is usually more of a task done by a maintainer. These people usually have intimate knowledge with how to release their stuff. So, the goal of STRTA of making it easier for contributors doesn't EXACTLY align with that.

That being said, I personally use STRTA in all of my projects FOR the normalization, and that could definitely include releasing. So there's a decent argument there.

I think the bigger issue is that releasing things usually takes a bit of interaction. So automating it might not really work?

**Comment by jesperronn** [comment]
> that releasing things usually takes a bit of interaction. So automating it might not really work?

Agree. About the automation of it,  there could be some links/pointers to interactive scripts, but the implementation has to be specific.

For instance, one could take this script to bump the version of a VERSION file:

https://gist.github.com/mareksuscak/1f206fbc3bb9d97dec9c/#file-bump-version-sh

and then combine it with language-specific, provider-specific release stuff. 

I think the 'usual' procedure is probably to copy from a similar project? I'd guess I would do this specifically depending on my needs: For a rubygem I would copy from an existing open-source rubygem, and similar for others.

I have also seen that some providers give multi-language examples of how to create a release file. ONe example is Bintray, that gives multiple examples on how to release with Gradle, Maven, Shell script, etc: https://github.com/bintray/bintray-examples/

Again, if you agree, the file `script/release` should merely serve as a placeholder. It would be beyond the limits of a project like this to maintain examples for all languages, to release to all providers ...

**Comment by technicalpickles** [comment]
I actually use a `script/release` for hubot: https://github.com/github/hubot/blob/master/script/release so I'd be :+1:  to mentioning it, if not adding it as a placeholder.

**Comment by maddox** [comment]
Should this prompt for input? 

The example could have it generating a gem and pushing it up to RubyGems. But should it bump the version too? If so, it would need an argument. None of the other scripts take any arguments, so this would be introducing something new. @technicalpickles have any feelings around that?

I have some scripts for iOS that push builds somewhere, and they take arguments. I could easily replace those with this. So this is just another example...

**Comment by technicalpickles** [comment]
I'm not sure we have strong enough patterns for this yet to make concrete examples.

Maybe we can just mention it separately from the ones we have a lot of experience with? ie "Other possibly useful scripts"

**Comment by mikemcquaid** [comment]
I think this is worth closing out as it's not something we use regularly internally and, as @technicalpickles pointed out, we have strong enough patterns for this yet to make concrete examples.
