### ISSUE TITLE
Q: why scripts/ instead of bin/?

### ISSUE THREAD

**Issue by dideler** [github/scripts-to-rule-them-all#17]
Just curious, is there a reason why the scripts are in the `scripts` directory as opposed to the `bin` directory which is common for (newer) Ruby projects?

One benefit I see of having both a `bin` and `scripts` directory is that if a developer prefers to have the project's `bin` in their PATH then they won't have the setup scripts from `script` cluttering their PATH.

**Comment by technicalpickles** [comment]
I started at GitHub after this pattern was established, so I'm not 100% sure on the original thinking. One reason I can imagine is that back in the day, Rails used to generate these commands, ie `script/server`, `script/console`, so you can think of this as mimicking this behavior in other language/frameworks. Another practical reason is that if you are using Ruby and Bundler with binstubs, it wants to install those into `bin`, so avoids having setup things and binstubs in the same place.

**Comment by dideler** [comment]
:bow:

**Comment by tvon** [comment]
FWIW, [Rails 4.2+ creates `bin/setup`](http://guides.rubyonrails.org/4_2_release_notes.html#railties-notable-changes) and [Rails 5 will get `bin/update`](https://github.com/rails/rails/pull/20972).

**Comment by srwaggon** [comment]
:two-cents: :necro:
Disclaimer: I am not and have never been as of writing this a Github Engineer and had no contributions in this decision.

One reason a person may choose 'script(s)' over 'bin' is that IIRC, 'bin' is short for 'binaries'. Scripts themselves are not binaries and this directory is not intended to contain a mixed-bag-of-stray binaries, so choosing that name would be a misnomer. IMO, calling the directory 'scripts' is the most honest, easily-discovered, non-surprising name.
