### ISSUE TITLE
The Curious Case of script/dbconsole

### ISSUE THREAD

**Issue by exalted** [github/scripts-to-rule-them-all#27]
Similar to Rails' `rails dbconsole`, should we have a `script/dbconsole`?

Let's talk!

**Comment by slacktracer** [comment]
I don't know much about Ruby (yet) and pretty much nothing about Rails BUT (and it's a big but) I think the option to access a database console could/should be an argument to the `script/console`.

The README suggests "A good pattern to support is having an optional argument" for handling different environments. Perhaps it's good enough for databases too.

Please enlighten me if I am missing something. What I know about `script/dbconsole` I just learned from http://rubyquicktips.com/post/16805618862/log-in-to-your-database-console-using-rails so I may be way off base here.

I see people wasn't very talkative around these parts so I thought it wouldn't hurt putting my two cents in.

**Comment by exalted** [comment]
I am going to close this, but please feel free to re-open if interested.
