### ISSUE TITLE
script/help

### ISSUE THREAD

**Issue by jesperronn** [github/scripts-to-rule-them-all#29]
In order to ease discoverability of the scripts I would like to have a general `scripts/help` command.

Especially for some projects with non-standard scripts. This way I don't have to peek into source comments of all files, but can just run `./script/help`

I have this in mind where I have non-standard projects (like `sync`, `deploy` or similar)

As maintainers and other users, what are your thoughts on this?

If this should be done, how would you implement in bash?

**Comment by exalted** [comment]
@jesperronn what would `script/help` do to you?

I was thinking, you could maybe output some brief, but right to the point, message with`script/foo --help`.

This is how almost every other command works; however, I was thinking something much shorter (similar to `whatis`'s output). Each `script/*` already contains a brief description of what it does, this would ideally only make it easier to access for users...

**Comment by technicalpickles** [comment]
We haven't done something like this for scripts-to-rule-them all in projects that I know of, but a pattern we've used elsewhere goes like this:

* files in a directory containing shell scripts have comments in them that start with `#/`
* a help script that reads that directory for executable shell scripts, and for each, read the comments with `#/` and use that as the documentation.
  * Calling without an args lists the scripts it knows about
  * Calling it with an arg shows the usage for that thing

**Comment by exalted** [comment]
> a help script that reads that directory for executable shell scripts, and for each, read the comments with #/ and use that as the documentation.

@technicalpickles that's nice. You don't have to maintain similar docs in two places: just update the docs inside the scripts themselves, and they will serve both for developers editing, and users via the command line. However, I feel like it's a better pattern with a `help` switch (e.g., `script/foo --help|-h`, or `script/foo help`).

Something like...

```bash
#!/usr/bin/env bash

#/ script/foo: Foo and much more! ;-)

[ "$1" == "--help" ] && grep -E '^#/' $(basename $0)

#  The rest of the foo business...
```

**Comment by dideler** [comment]
I was thinking about a README in every* directory but I much more prefer the idea of (re)using the docs defined in the scripts as it's less likely to go stale.

<sup>* read: most</sup>

**Comment by MikeMcQuaid** [comment]
> We haven't done something like this for scripts-to-rule-them all in projects that I know of, but a pattern we've used elsewhere goes like this:

Thanks for the issue but passing on this given @technicalpickles comment above; this isn't part of this pattern we use.
