### ISSUE TITLE
do you import the scripts in this repo in your other repos?

### ISSUE THREAD

**Issue by AlJohri** [github/scripts-to-rule-them-all#34]
do you run script/bootstrap in this directory at the top of the project specific script/bootstrap? also curious if you have any ideas how to share bash functions across projects in general

I imagine using this snippet

```bash
if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production
  }
fi
```

in every/most projects

**Comment by exalted** [comment]
@AlJohri assuming I get correctly the first part of your question; these scripts are meant to be copy & pasted (so to speak) into individual projects, ideally at the root level, and used in that context.

Check out https://github.com/github/github-ldap/tree/master/script for instance.

**Comment by AlJohri** [comment]
Cool. That mostly answered my question. Have you had any concerns regarding copying and pasting and wanted to move toward sharing functions or is that a nonissue?

I imagine doing a lot of copypasta if I went this route. Like check if Python is installed, make sure it's at least version X, make sure virtualenvwrapper is set up properly, create the virtual environment if it doesn't exist, install brewfile dependencies, createdb/user if the app needs it etc. takes lots of boilerplate to do those things

**Comment by exalted** [comment]
I personally don't have much to suggest here. Sorry.

I guess the trick here would be to create a template/boilerplate [that contains `script/`) from which to create new projects.

This way you would get the bulk of the features that are shared between projects for free. For instance, many frameworks come with a CLI that let you create new a project from a template (e.g., `rails new foo`).

**Comment by maddox** [comment]
These scripts are designed to be copy and pasted into your projects. Every project has their own special needs, so vendoring your own from another repo into every project would most likely never really work out well. 

The whole points of Scripts to Rule Them All is that: all projects have their own special needs, but all projects need to do these things. Make these things callable from a normalized set of named scripts, and developers no longer need to know the nitty gritty details about things like "how do the tests run?". They just run `script/test`.

These scripts serve as a base. You will most likely be changing the contents and what happens inside them on a per project basis. In fact, this whole repo isn't really about the content of the scripts, as much as it is about setting standards in naming them and doing what they do.

I hope this helps!

**Comment by AlJohri** [comment]
Cool, that helps. Thanks guys!
