### ISSUE TITLE
Best practices for supporting Windows users?

### ISSUE THREAD

**Issue by zeke** [github/scripts-to-rule-them-all#42]
I work on a private Node.js-based project that makes use of the Scripts To Rule Them All methodology. Our project has historically been run only in macOS and Linux environments, but we will soon be welcoming some contributors who use MS Windows for development.

Some of our scripts are bash (or `sh`):

```sh
#!/bin/bash

# do some setup stuff
# run the server
```

And some of them are Node.js scripts:

```js
#!/usr/bin/env node

const path = require('path')
// etc...
```

Our project's README recommends running scripts like `script/bootstrap` and `script/server`. However as we cater to Windows developers, I think we may want to document the `npm run` variants of those scripts like `npm start` and `npm run boostrap` instead, as they should work consistently across all platforms.

My questions:

- Can shell scripts be easily run in Windows nowadays? I think it's possible on Windows 10 with [Windows Subsystem of Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) installed, but setting that up might be a lot to ask of new contributors.
- If we can't run shell scripts on Windows, should we shy away from writing bash and instead write all our scripts in Node.js?

cc @github/product-docs-engineering

**Comment by exalted** [comment]
:two-cents: I used to install GitHub Desktop on Windows which installed a nice Bash emulator, ready to use in Windows. I don't use Windows nowadays, but perhaps something you could consider looking into?

**Comment by MikeMcQuaid** [comment]
> * Can shell scripts be easily run in Windows nowadays? I think it's possible on Windows 10 with [Windows Subsystem of Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) installed, but setting that up might be a lot to ask of new contributors.

That would be understanding of the current best way to run them on Windows.

> * If we can't run shell scripts on Windows, should we shy away from writing bash and instead write all our scripts in Node.js?

NodeJS or some other portable runtime: yes, seems sensible.

Happy to continue discussion here but closing this out as it's not an actionable change for this repository as-is which documents an internal GitHub development pattern and shouldn't change these scripts until the majority of our internal repositories use e.g. NodeJS instead of Bash for writing these scripts.

**Comment by zeke** [comment]
Thanks for the input.

>  it's not an actionable change for this repository as-is

Maybe the actionable change here should be an update to the README in this repo to mention that this pattern does not apply for Windows development. @MikeMcQuaid would you be open to a PR adding that?

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid would you be open to a PR adding that?

Yes, please, sounds great!

**Comment by TheFlagCourier** [comment]
GitBash from Git for Windows (not GitHub Desktop) provides a minimal MinGW environment. Perhaps that deserves an honorable mention?

**Comment by zeke** [comment]
@TheFlagCourier do you use GitBash? If so, when you run a script, do you have to prefix it with the `bash` binary, e.g. `bash script/boostrap`? Or can you just invoke the script with `script/bootstrap`?
