### ISSUE TITLE
Nodejs scripts

### ISSUE THREAD

**Issue by 404answernotfound** [github/scripts-to-rule-them-all#53]
Didn't know if I could fork and make a PR for a nodejs set of scripts that Im working on, based on your templates. For now I did a repo on my profile specifying that this is the main repo from which it originated.

Could you tell me how I could contribute the scripts once they are done? Thanks!

Repo here, just in case https://github.com/404answernotfound/script-to-rule-them-all-nodejs

**Comment by MikeMcQuaid** [comment]
Nice work on your fork! We're not interested in merging back here just because we wouldn't use that internally.

**Comment by 404answernotfound** [comment]
> Nice work on your fork! We're not interested in merging back here just because we wouldn't use that internally.

Thank you for the answer Mike! Have a great day :D
