### ISSUE TITLE
Why not using a makefile ?

### ISSUE THREAD

**Issue by Nasga** [github/scripts-to-rule-them-all#8]
Why not using a makefile with targets : bootstrap, setup, update, server, test, cibuild, console ?

A makefile could also use existing scripts.

With a simple make, you could trigger bootstrap, setup, server targets to build your dev env in a single command.

**Comment by samlambert** [comment]
Make would be an option but I like this pattern to universally tie project tasks together. Some scripts call the scripts in this repo meaning by adding make we'd be adding a third access pattern (make, direct script/foo, and calling in a script).

**Comment by jbarnette** [comment]
@Nasga You could absolutely use a makefile with some standard targets to achieve the same goals. Many of our teams don't use `make` in their daily workflows, so we decided to use executable scripts at well-known locations instead.

**Comment by Nasga** [comment]
Thanks for your feedback.

**Comment by casey** [comment]
[just](https://github.com/casey/just) would be a good alternative to `make` here, that might actually improve ergonomics and discoverability.
